export const countries = [
  { sigla: "AF", nome: "Afeganistão" },
  { sigla: "AL", nome: "Albânia" },
  { sigla: "DZ", nome: "Argélia" },
  { sigla: "AD", nome: "Andorra" },
  { sigla: "AO", nome: "Angola" },
  { sigla: "AR", nome: "Argentina" },
  { sigla: "AM", nome: "Armênia" },
  { sigla: "AU", nome: "Austrália" },
  { sigla: "AT", nome: "Áustria" },
  { sigla: "AZ", nome: "Azerbaijão" },
  { sigla: "BS", nome: "Bahamas" },
  { sigla: "BH", nome: "Bahrein" },
  { sigla: "BD", nome: "Bangladesh" },
  { sigla: "BB", nome: "Barbados" },
  { sigla: "BY", nome: "Belarus (Bielorrússia)" },
  { sigla: "BE", nome: "Bélgica" },
  { sigla: "BZ", nome: "Belize" },
  { sigla: "BJ", nome: "Benin" },
  { sigla: "BT", nome: "Butão" },
  { sigla: "BO", nome: "Bolívia" },
  { sigla: "BA", nome: "Bósnia e Herzegovina" },
  { sigla: "BW", nome: "Botsuana" },
  { sigla: "BR", nome: "Brasil" },
  { sigla: "BN", nome: "Brunei" },
  { sigla: "BG", nome: "Bulgária" },
  { sigla: "BF", nome: "Burkina Faso" },
  { sigla: "BI", nome: "Burundi" },
  { sigla: "KH", nome: "Camboja" },
  { sigla: "CM", nome: "Camarões" },
  { sigla: "CA", nome: "Canadá" },
  { sigla: "CV", nome: "Cabo Verde" },
  { sigla: "CF", nome: "República Centro-Africana" },
  { sigla: "TD", nome: "Chade" },
  { sigla: "CL", nome: "Chile" },
  { sigla: "CN", nome: "China" },
  { sigla: "CO", nome: "Colômbia" },
  { sigla: "KM", nome: "Comores" },
  { sigla: "CG", nome: "Congo" },
  { sigla: "CD", nome: "República Democrática do Congo" },
  { sigla: "CR", nome: "Costa Rica" },
  { sigla: "HR", nome: "Croácia" },
  { sigla: "CU", nome: "Cuba" },
  { sigla: "CY", nome: "Chipre" },
  { sigla: "CZ", nome: "República Tcheca" },
  { sigla: "DK", nome: "Dinamarca" },
  { sigla: "DJ", nome: "Djibuti" },
  { sigla: "DM", nome: "Dominica" },
  { sigla: "DO", nome: "República Dominicana" },
  { sigla: "EC", nome: "Equador" },
  { sigla: "EG", nome: "Egito" },
  { sigla: "SV", nome: "El Salvador" },
  { sigla: "GQ", nome: "Guiné Equatorial" },
  { sigla: "ER", nome: "Eritreia" },
  { sigla: "EE", nome: "Estônia" },
  { sigla: "ET", nome: "Etiópia" },
  { sigla: "FJ", nome: "Fiji" },
  { sigla: "FI", nome: "Finlândia" },
  { sigla: "FR", nome: "França" },
  { sigla: "GA", nome: "Gabão" },
  { sigla: "GM", nome: "Gâmbia" },
  { sigla: "GE", nome: "Geórgia" },
  { sigla: "DE", nome: "Alemanha" },
  { sigla: "GH", nome: "Gana" },
  { sigla: "GR", nome: "Grécia" },
  { sigla: "GD", nome: "Granada" },
  { sigla: "GT", nome: "Guatemala" },
  { sigla: "GN", nome: "Guiné" },
  { sigla: "GW", nome: "Guiné-Bissau" },
  { sigla: "GY", nome: "Guiana" },
  { sigla: "HT", nome: "Haiti" },
  { sigla: "HN", nome: "Honduras" },
  { sigla: "HU", nome: "Hungria" },
  { sigla: "IS", nome: "Islândia" },
  { sigla: "IN", nome: "Índia" },
  { sigla: "ID", nome: "Indonésia" },
  { sigla: "IR", nome: "Irã" },
  { sigla: "IQ", nome: "Iraque" },
  { sigla: "IE", nome: "Irlanda" },
  { sigla: "IL", nome: "Israel" },
  { sigla: "IT", nome: "Itália" },
  { sigla: "JM", nome: "Jamaica" },
  { sigla: "JP", nome: "Japão" },
  { sigla: "JO", nome: "Jordânia" },
  { sigla: "KZ", nome: "Cazaquistão" },
  { sigla: "KE", nome: "Quênia" },
  { sigla: "KI", nome: "Kiribati" },
  { sigla: "KP", nome: "Coreia do Norte" },
  { sigla: "KR", nome: "Coreia do Sul" },
  { sigla: "KW", nome: "Kuwait" },
  { sigla: "KG", nome: "Quirguistão" },
  { sigla: "LA", nome: "Laos" },
  { sigla: "LV", nome: "Letônia" },
  { sigla: "LB", nome: "Líbano" },
  { sigla: "LS", nome: "Lesoto" },
  { sigla: "LR", nome: "Libéria" },
  { sigla: "LY", nome: "Líbia" },
  { sigla: "LI", nome: "Liechtenstein" },
  { sigla: "LT", nome: "Lituânia" },
  { sigla: "LU", nome: "Luxemburgo" },
  { sigla: "MK", nome: "Macedônia do Norte" },
  { sigla: "MG", nome: "Madagascar" },
  { sigla: "MW", nome: "Malawi" },
  { sigla: "MY", nome: "Malásia" },
  { sigla: "MV", nome: "Maldivas" },
  { sigla: "ML", nome: "Mali" },
  { sigla: "MT", nome: "Malta" },
  { sigla: "MH", nome: "Ilhas Marshall" },
  { sigla: "MR", nome: "Mauritânia" },
  { sigla: "MU", nome: "Maurícia" },
  { sigla: "MX", nome: "México" },
  { sigla: "FM", nome: "Micronésia" },
  { sigla: "MD", nome: "Moldávia" },
  { sigla: "MC", nome: "Mônaco" },
  { sigla: "MN", nome: "Mongólia" },
  { sigla: "ME", nome: "Montenegro" },
  { sigla: "MA", nome: "Marrocos" },
  { sigla: "MZ", nome: "Moçambique" },
  { sigla: "MM", nome: "Myanmar" },
  { sigla: "NA", nome: "Namíbia" },
  { sigla: "NR", nome: "Nauru" },
  { sigla: "NP", nome: "Nepal" },
  { sigla: "NL", nome: "Países Baixos" },
  { sigla: "NZ", nome: "Nova Zelândia" },
  { sigla: "NI", nome: "Nicarágua" },
  { sigla: "NE", nome: "Níger" },
  { sigla: "NG", nome: "Nigéria" },
  { sigla: "NO", nome: "Noruega" },
  { sigla: "OM", nome: "Omã" },
  { sigla: "PK", nome: "Paquistão" },
  { sigla: "PW", nome: "Palau" },
  { sigla: "PS", nome: "Palestina" },
  { sigla: "PA", nome: "Panamá" },
  { sigla: "PG", nome: "Papua Nova Guiné" },
  { sigla: "PY", nome: "Paraguai" },
  { sigla: "PE", nome: "Peru" },
  { sigla: "PH", nome: "Filipinas" },
  { sigla: "PL", nome: "Polônia" },
  { sigla: "PT", nome: "Portugal" },
  { sigla: "QA", nome: "Catar" },
  { sigla: "RO", nome: "Romênia" },
  { sigla: "RU", nome: "Rússia" },
  { sigla: "RW", nome: "Ruanda" },
  { sigla: "KN", nome: "São Cristóvão e Nevis" },
  { sigla: "LC", nome: "Santa Lúcia" },
  { sigla: "VC", nome: "São Vicente e Granadinas" },
  { sigla: "WS", nome: "Samoa" },
  { sigla: "SM", nome: "San Marino" },
  { sigla: "ST", nome: "São Tomé e Príncipe" },
  { sigla: "SA", nome: "Arábia Saudita" },
  { sigla: "SN", nome: "Senegal" },
  { sigla: "RS", nome: "Sérvia" },
  { sigla: "SC", nome: "Seychelles" },
  { sigla: "SL", nome: "Serra Leoa" },
  { sigla: "SG", nome: "Singapura" },
  { sigla: "SK", nome: "Eslováquia" },
  { sigla: "SI", nome: "Eslovênia" },
  { sigla: "SB", nome: "Ilhas Salomão" },
  { sigla: "SO", nome: "Somália" },
  { sigla: "ZA", nome: "África do Sul" },
  { sigla: "SS", nome: "Sudão do Sul" },
  { sigla: "ES", nome: "Espanha" },
  { sigla: "LK", nome: "Sri Lanka" },
  { sigla: "SD", nome: "Sudão" },
  { sigla: "SR", nome: "Suriname" },
  { sigla: "SZ", nome: "Suazilândia" },
  { sigla: "SE", nome: "Suécia" },
  { sigla: "CH", nome: "Suíça" },
  { sigla: "SY", nome: "Síria" },
  { sigla: "TW", nome: "Taiwan" },
  { sigla: "TJ", nome: "Tajiquistão" },
  { sigla: "TZ", nome: "Tanzânia" },
  { sigla: "TH", nome: "Tailândia" },
  { sigla: "TL", nome: "Timor-Leste" },
  { sigla: "TG", nome: "Togo" },
  { sigla: "TO", nome: "Tonga" },
  { sigla: "TT", nome: "Trinidad e Tobago" },
  { sigla: "TN", nome: "Tunísia" },
  { sigla: "TR", nome: "Turquia" },
  { sigla: "TM", nome: "Turcomenistão" },
  { sigla: "TV", nome: "Tuvalu" },
  { sigla: "UG", nome: "Uganda" },
  { sigla: "UA", nome: "Ucrânia" },
  { sigla: "AE", nome: "Emirados Árabes Unidos" },
  { sigla: "GB", nome: "Reino Unido" },
  { sigla: "US", nome: "Estados Unidos" },
  { sigla: "UY", nome: "Uruguai" },
  { sigla: "UZ", nome: "Uzbequistão" },
  { sigla: "VU", nome: "Vanuatu" },
  { sigla: "VA", nome: "Vaticano" },
  { sigla: "VE", nome: "Venezuela" },
  { sigla: "VN", nome: "Vietnã" },
  { sigla: "YE", nome: "Iêmen" },
  { sigla: "ZM", nome: "Zâmbia" },
  { sigla: "ZW", nome: "Zimbábue" },
];
