export const americanStates = [
  { sigla: "AL", nome: "Alabama" },
  { sigla: "AK", nome: "Alaska" },
  { sigla: "AZ", nome: "Arizona" },
  { sigla: "AR", nome: "Arkansas" },
  { sigla: "CA", nome: "Califórnia" },
  { sigla: "CO", nome: "Colorado" },
  { sigla: "CT", nome: "Connecticut" },
  { sigla: "DE", nome: "Delaware" },
  { sigla: "FL", nome: "Flórida" },
  { sigla: "GA", nome: "Geórgia" },
  { sigla: "HI", nome: "Havaí" },
  { sigla: "ID", nome: "Idaho" },
  { sigla: "IL", nome: "Illinois" },
  { sigla: "IN", nome: "Indiana" },
  { sigla: "IA", nome: "Iowa" },
  { sigla: "KS", nome: "Kansas" },
  { sigla: "KY", nome: "Kentucky" },
  { sigla: "LA", nome: "Louisiana" },
  { sigla: "ME", nome: "Maine" },
  { sigla: "MD", nome: "Maryland" },
  { sigla: "MA", nome: "Massachusetts" },
  { sigla: "MI", nome: "Michigan" },
  { sigla: "MN", nome: "Minnesota" },
  { sigla: "MS", nome: "Mississippi" },
  { sigla: "MO", nome: "Missouri" },
  { sigla: "MT", nome: "Montana" },
  { sigla: "NE", nome: "Nebraska" },
  { sigla: "NV", nome: "Nevada" },
  { sigla: "NH", nome: "New Hampshire" },
  { sigla: "NJ", nome: "New Jersey" },
  { sigla: "NM", nome: "Novo México" },
  { sigla: "NY", nome: "Nova York" },
  { sigla: "NC", nome: "Carolina do Norte" },
  { sigla: "ND", nome: "Dakota do Norte" },
  { sigla: "OH", nome: "Ohio" },
  { sigla: "OK", nome: "Oklahoma" },
  { sigla: "OR", nome: "Oregon" },
  { sigla: "PA", nome: "Pensilvânia" },
  { sigla: "RI", nome: "Rhode Island" },
  { sigla: "SC", nome: "Carolina do Sul" },
  { sigla: "SD", nome: "Dakota do Sul" },
  { sigla: "TN", nome: "Tennessee" },
  { sigla: "TX", nome: "Texas" },
  { sigla: "UT", nome: "Utah" },
  { sigla: "VT", nome: "Vermont" },
  { sigla: "VA", nome: "Virgínia" },
  { sigla: "WA", nome: "Washington" },
  { sigla: "WV", nome: "Virgínia Ocidental" },
  { sigla: "WI", nome: "Wisconsin" },
  { sigla: "WY", nome: "Wyoming" },
];
